<?php if (!defined('BASEPATH')) exit('No direct script access allowed');

class PageController extends CI_Controller
{
    public function __construct()
    {
        parent::__construct();
    }

    public function header(){

        $data['title'] = 'Vendor Management Portal';

        $this->load->view('includes/header', $data);
    }

    public function bodyContent(){

        $this->header();
        $this->load->view('includes/home');
    }

    public function footerContent(){
        $this->load->view('includes/footer');
    }

    /**
     * @param object $load
     */
    public function setLoad($load)
    {
        $this->load = $load;
    }

    public static function get_instance()
    {
        return parent::get_instance(); // TODO: Change the autogenerated stub
    }

}
